Vagrant.configure("2") do |config|

  config.vm.define "sonar" do |sonar|
    sonar.vm.box = "cyberxml/c7vb52"
    sonar.vm.hostname = "sonar"
    config.vm.provider :virtualbox do |vb|
        vb.customize [ "modifyvm", :id, "--memory", "4096" ]
    end
    sonar.vm.network "forwarded_port", guest: 9000, host: 9000
    sonar.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    sonar.vm.provision "ansible_local", run: 'once' do |ansible|
      ansible.galaxy_role_file = "conf/sonar/requirements.yml"
      ansible.playbook = "conf/sonar/sonar.yml"
      ansible.sudo = true
    end
  end

end
